#------------stage 1---------
FROM node:24-alpine AS builder
WORKDIR /app
COPY package.json .
RUN npm install
COPY frontend ./frontend
COPY css ./css
COPY js ./js
COPY images ./images
RUN npm run build

#--------stage 2------
FROM nginx:1.31.2-trixie

COPY --from=builder /app/dist /usr/share/nginx/html
COPY trek_mate_nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
